/**
 * Google Gemini AI Summary Service
 * Generates plain-language bill summaries with balanced perspective
 *
 * Model: gemini-2.0-flash (free tier: 15 req/min, 1M tokens/day)
 * Summaries are cached for 7 days — generate once, never pay twice
 * Every summary is tagged with model version and timestamp
 *
 * IMPORTANT: All AI-generated content must display the disclaimer.
 */

import { config } from '@/lib/config';
import { getAPICache, CACHE_TTL } from '@/lib/api-cache';

const GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';

export const AI_DISCLAIMER = 'This summary was generated by AI to help explain this bill in plain language. AI can make mistakes or reflect bias in its training data. Always verify with the primary source at Congress.gov.';

interface AISummary {
  summary: string;
  supportersView: string;
  opponentsView: string;
  model: string;
  modelVersion: string;
  generatedAt: string;
  disclaimer: string;
  billId: string;
}

/**
 * Generate a plain-language AI summary with balanced perspectives
 * Only for bills from 2026 onward — older bills use CRS summaries
 */
export async function generateBillSummary(billData: {
  id: string;
  title: string;
  summary: string | null;
  sponsors: Array<{ fullName: string; party: string; state: string }>;
  policyArea: string;
  introducedDate: string;
}): Promise<AISummary | null> {
  // Only summarize bills from the 119th Congress onward (2025+)
  const year = parseInt(billData.introducedDate?.substring(0, 4) || '0');
  if (year < 2025) return null;

  if (!config.geminiApiKey) {
    console.warn('Gemini API key not configured — skipping AI summary');
    return null;
  }

  const cache = getAPICache();
  const cacheKey = `ai-summary:${billData.id}`;

  const cached = cache.get<AISummary>(cacheKey);
  if (cached) return cached;

  const prompt = buildPrompt(billData);

  try {
    const response = await fetch(`${GEMINI_URL}?key=${config.geminiApiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.3,
          maxOutputTokens: 1024,
          responseMimeType: 'application/json',
        },
      }),
      signal: AbortSignal.timeout(20000),
    });

    if (!response.ok) {
      console.error('Gemini API error:', response.status);
      return null;
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) return null;

    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch {
      // If JSON parsing fails, use the raw text as summary
      parsed = { summary: text, supportersView: '', opponentsView: '' };
    }

    const result: AISummary = {
      summary: parsed.summary || '',
      supportersView: parsed.supportersView || '',
      opponentsView: parsed.opponentsView || '',
      model: 'gemini-2.0-flash',
      modelVersion: 'v1beta',
      generatedAt: new Date().toISOString(),
      disclaimer: AI_DISCLAIMER,
      billId: billData.id,
    };

    cache.set(cacheKey, result, CACHE_TTL.AI_SUMMARY);
    return result;
  } catch (error) {
    console.error('Gemini summary generation failed:', error);
    return null;
  }
}

function buildPrompt(billData: {
  title: string;
  summary: string | null;
  sponsors: Array<{ fullName: string; party: string; state: string }>;
  policyArea: string;
}): string {
  const sponsorText = billData.sponsors
    .map(s => `${s.fullName} (${s.party}-${s.state})`)
    .join(', ');

  return `You are a non-partisan civic education tool. Analyze this federal bill and provide a balanced summary.

BILL: ${billData.title}
POLICY AREA: ${billData.policyArea}
SPONSORS: ${sponsorText}
${billData.summary ? `CRS SUMMARY: ${billData.summary.substring(0, 2000)}` : ''}

Respond in JSON with these fields:
{
  "summary": "A 2-3 sentence plain-English explanation of what this bill does and why it matters. Write for someone with no legal background. Be factual and specific about what would change.",
  "supportersView": "1-2 sentences explaining what this bill means from a left-leaning / progressive / Democratic perspective. What do they see as the benefit or concern? Be specific and factual.",
  "opponentsView": "1-2 sentences explaining what this bill means from a right-leaning / conservative / Republican perspective. What do they see as the benefit or concern? Be specific and factual."
}

Rules:
- Be factual and balanced. Do not advocate for either side.
- Frame supportersView as "What this means for the Left" and opponentsView as "What this means for the Right."
- Both sides may support OR oppose a bill — don't assume Left=support and Right=oppose.
- Use plain English — no legal jargon.
- Be specific about impacts, not vague generalities.
- If you don't have enough information, say "Perspectives on this bill are not yet widely documented."
- Do not make up facts. Only state what can be inferred from the bill title, policy area, and summary.`;
}
