/**
 * Hugging Face Inference API — Free fallback for AI summaries
 * No billing required, 100K chars/month, 60 req/min
 * Uses Mistral-7B-Instruct or similar open model
 *
 * Docs: https://huggingface.co/docs/inference-providers
 */

import { getAPICache, CACHE_TTL } from '@/lib/api-cache';
import { config } from '@/lib/config';

const HF_API_URL = 'https://router.huggingface.co/v1/chat/completions';
const HF_MODEL = 'Qwen/Qwen2.5-7B-Instruct';

export const AI_DISCLAIMER = 'This summary was generated by AI to help explain this bill in plain language. AI can make mistakes or reflect bias in its training data. Always verify with the primary source at Congress.gov.';

interface AISummary {
  summary: string;
  supportersView: string;
  opponentsView: string;
  model: string;
  modelVersion: string;
  generatedAt: string;
  disclaimer: string;
  billId: string;
}

/**
 * Generate a bill summary using Hugging Face free inference
 */
export async function generateBillSummaryHF(billData: {
  id: string;
  title: string;
  summary: string | null;
  sponsors: Array<{ fullName: string; party: string; state: string }>;
  policyArea: string;
  introducedDate: string;
}): Promise<AISummary | null> {
  // Only summarize 2025+ bills
  const year = parseInt(billData.introducedDate?.substring(0, 4) || '0');
  if (year < 2025) return null;

  const hfToken = config.huggingfaceToken;
  if (!hfToken) {
    console.warn('Hugging Face token not configured — skipping AI summary');
    return null;
  }

  const cache = getAPICache();
  const cacheKey = `ai-summary:${billData.id}`;

  const cached = cache.get<AISummary>(cacheKey);
  if (cached) return cached;

  const prompt = buildPrompt(billData);

  try {
    const response = await fetch(HF_API_URL, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${hfToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: HF_MODEL,
        messages: [
          {
            role: 'system',
            content: 'You are a non-partisan civic education tool. You respond only in valid JSON. Do not include markdown code fences or any text outside the JSON object.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        max_tokens: 800,
        temperature: 0.3,
      }),
      signal: AbortSignal.timeout(30000),
    });

    if (!response.ok) {
      console.error('HuggingFace API error:', response.status, await response.text().catch(() => ''));
      return null;
    }

    const data = await response.json();
    const text = data.choices?.[0]?.message?.content?.trim();

    if (!text) return null;

    let parsed;
    try {
      // Strip markdown code fences if present
      const cleaned = text.replace(/^```json?\n?/i, '').replace(/\n?```$/i, '').trim();
      parsed = JSON.parse(cleaned);
    } catch {
      // If JSON parsing fails, try to extract something useful
      parsed = { summary: text.substring(0, 500), supportersView: '', opponentsView: '' };
    }

    const result: AISummary = {
      summary: parsed.summary || '',
      supportersView: parsed.supportersView || parsed.leftView || '',
      opponentsView: parsed.opponentsView || parsed.rightView || '',
      model: HF_MODEL,
      modelVersion: 'huggingface-router',
      generatedAt: new Date().toISOString(),
      disclaimer: AI_DISCLAIMER,
      billId: billData.id,
    };

    cache.set(cacheKey, result, CACHE_TTL.AI_SUMMARY);
    return result;
  } catch (error) {
    console.error('HuggingFace summary generation failed:', error);
    return null;
  }
}

function buildPrompt(billData: {
  title: string;
  summary: string | null;
  sponsors: Array<{ fullName: string; party: string; state: string }>;
  policyArea: string;
}): string {
  const sponsorText = billData.sponsors
    .map(s => `${s.fullName} (${s.party}-${s.state})`)
    .join(', ');

  return `Analyze this federal bill and respond with ONLY a JSON object (no markdown, no code fences, no extra text):

BILL: ${billData.title}
POLICY AREA: ${billData.policyArea}
SPONSORS: ${sponsorText}
${billData.summary ? `CRS SUMMARY: ${billData.summary.substring(0, 1500)}` : ''}

{
  "summary": "A 2-3 sentence plain-English explanation of what this bill does and why it matters. Be factual and specific.",
  "supportersView": "1-2 sentences on what this means from a left-leaning / progressive / Democratic perspective. Be specific and factual.",
  "opponentsView": "1-2 sentences on what this means from a right-leaning / conservative / Republican perspective. Be specific and factual."
}

Rules:
- Be factual and balanced. Both sides may support OR oppose.
- Use plain English, no legal jargon.
- If unsure, say "Perspectives on this bill are not yet widely documented."
- Do not make up facts.`;
}
