'use client';

interface AISummaryProps {
  summary: string;
  supportersView: string;
  opponentsView: string;
  model: string;
  generatedAt: string;
  disclaimer: string;
}

export default function AISummaryCard({ summary, supportersView, opponentsView, model, generatedAt, disclaimer }: AISummaryProps) {
  return (
    <div className="w-full">
      <WhatThisBillDoes summary={summary} />
      <div className="mt-6">
        <LeftRightImpact
          supportersView={supportersView}
          opponentsView={opponentsView}
          model={model}
          generatedAt={generatedAt}
          disclaimer={disclaimer}
        />
      </div>
    </div>
  );
}

export function WhatThisBillDoes({ summary }: { summary: string }) {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 lg:p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">What This Bill Does</h2>
      <p className="text-lg text-gray-800 leading-relaxed">{summary}</p>
    </div>
  );
}

interface LeftRightProps {
  supportersView: string;
  opponentsView: string;
  model: string;
  generatedAt: string;
  disclaimer: string;
}

export function LeftRightImpact({ supportersView, opponentsView, model, generatedAt, disclaimer }: LeftRightProps) {
  return (
    <div>
      <div className="grid md:grid-cols-2 gap-6 mb-4">
        {/* Left / Democrats */}
        <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-xl border border-blue-200 p-6 lg:p-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center">
              <span className="text-white font-bold text-lg">L</span>
            </div>
            <h3 className="text-xl font-bold text-blue-900">What This Means for the Left</h3>
          </div>
          <p className="text-blue-900 leading-relaxed">
            {supportersView || 'Perspectives on this bill are not yet widely documented.'}
          </p>
        </div>

        {/* Right / Republicans */}
        <div className="bg-gradient-to-br from-red-50 to-red-100 rounded-xl border border-red-200 p-6 lg:p-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-10 h-10 rounded-full bg-red-600 flex items-center justify-center">
              <span className="text-white font-bold text-lg">R</span>
            </div>
            <h3 className="text-xl font-bold text-red-900">What This Means for the Right</h3>
          </div>
          <p className="text-red-900 leading-relaxed">
            {opponentsView || 'Perspectives on this bill are not yet widely documented.'}
          </p>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg px-4 py-3">
        <p className="text-xs text-amber-800">
          <span className="font-bold">AI Disclosure:</span> {disclaimer}
        </p>
        <p className="text-xs text-amber-600 mt-1">
          Generated by {model} on {new Date(generatedAt).toLocaleDateString()}
        </p>
      </div>
    </div>
  );
}
